version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=parola
  node:
    build: .
    ports:
      - 80:80
    tty: true
    volumes:
      - .:/usr/src/app
